export const products = [
  {
    id:1,
    name: "iPhone 13 100",
    brand: "Apple",
    storage: "128GB",
    color: "Midnight Green",
    price: 100.99,
    image: "https://example.com/iphone13.jpg",
  },
  {
    id:2,
    name: "iPhone 13 200",
    brand: "Apple",
    storage: "128GB",
    color: "Midnight Green",
    price: 200.99,
    image: "https://example.com/iphone13.jpg",
  },
  {
    id:3,
    name: "iPhone 13 300",
    brand: "Apple",
    storage: "128GB",
    color: "Midnight Green",
    price: 300.99,
    image: "https://example.com/iphone13.jpg",
  },
  {
    id:4,
    name: "Samsung Galaxy S21",
    brand: "Samsung",
    storage: "256GB",
    color: "Phantom Gray",
    price: 899.95,
    image: "https://example.com/galaxys21.jpg",
  },
  {   id:5,
    name: "Google Pixel 6",
    brand: "Google",
    storage: "128GB",
    color: "Clearly White",
    price: 400.0,
    image: "https://example.com/pixel6.jpg",
  },
  {
    id:6,
    name: "OnePlus 9 Pro",
    brand: "OnePlus",
    storage: "256GB",
    color: "Morning Mist",
    price: 600.0,
    image: "https://example.com/oneplus9pro.jpg",
  },
  {
    id:7,
    name: "Xiaomi Mi 11",
    brand: "Xiaomi",
    storage: "128GB",
    color: "Cosmic Black",
    price: 749.99,
    image: "https://example.com/mi11.jpg",
  },
];
